services:
  - type: web
    name: ops-tools
    env: python
    plan: free
    healthCheckPath: /healthz
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
